declare const BMap: any;
declare const BMapLib: any;
declare const BMAP_ANCHOR_TOP_LEFT: string;
declare const BMAP_ANCHOR_TOP_RIGHT: string;
declare const BMAP_ANCHOR_BOTTOM_LEFT: string;
declare const BMAP_ANCHOR_BOTTOM_RIGHT: string;
declare const BMAP_DRAWING_CIRCLE: string;
declare const BMAP_DRAWING_RECTANGLE: string;
declare const BMap_Symbol_SHAPE_POINT: string;
declare const BMAP_ANIMATION_BOUNCE: string;
export { BMap, BMapLib, BMAP_ANCHOR_TOP_LEFT, BMAP_ANCHOR_TOP_RIGHT, BMAP_ANCHOR_BOTTOM_LEFT, BMAP_ANCHOR_BOTTOM_RIGHT, BMAP_DRAWING_CIRCLE, BMAP_DRAWING_RECTANGLE, BMap_Symbol_SHAPE_POINT, BMAP_ANIMATION_BOUNCE };
